#
# Copyright (c) 2020 - 2022
#
# Updated: 03/13/2022 Eliminater74
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# Description: Build OpenWrt using GitHub Actions
#
# "SOURCE_DIRECTORY_B": "openwrt/bin/targets/mediatek/mt7622/kmods/$KMOD_DIR",

name: Build Linksys e8450 (AKA Belkin rt3200) firmware
on:
  workflow_dispatch:
#  schedule:
        # * is a special character in YAML so you have to quote this string
        # el primer día de cada mes a las 00:00
#    - cron:  '00 00 01 * *'

jobs:
  trigger-nightly-builds:
    if: github.event != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PAT }}
          repo: wrt32x
          owner: zow2023
          event_type: repository_dispatch
          message: |
            {
              "HARDWARE_DEVICE": "e8450",
              "HARDWARE_ID": "e8450",
              "SOURCE_DIRECTORY_A": "openwrt/bin/packages/arm_cortex-a9_vfpv3-d16",
              "SOURCE_DIRECTORY_B": "openwrt/bin/targets/mediatek/mt7622/kmods",
              "ARQUITECTURA": "mediatek/mt7622/",
              "config_file": "rt3200.config",
              "ISP": "none"
            }
